version: 2
updates:

    - package-ecosystem: npm
      cooldown:
        default-days: 7
      directory: '/'
      schedule:
        interval: monthly
      groups:
        dev-deps:
          dependency-type: development
        actions:
          patterns:
          - "@actions/*"

    - package-ecosystem: github-actions
      directory: /
      schedule:
        interval: monthly
