name: 'Bump version from tag'
description: 'Bumps a semver version from tag or fallback version'
inputs:
  level:
    description: 'Used to bump the version related to semver'
    required: true
  github_secret:
    description: 'Secret for github'
    required: true
  build_number:
    description: 'If supplied, we will build an output with this version number in the form of {version}-alpha.{build_number}, default is 0'
    required: false
  fallback_tag:
    description: 'If supplied and no tags are found, we will use this version'
    required: false
outputs:
  old_version:
    description: 'The current latest tag of the repository'
  new_version:
    description: 'The new tag created by SemVer'
  pre_release_version:
    description: 'Pre release version built from {new_version}-alpha.{build_number}'
runs:
  using: 'node16'
  main: 'dist/index.js'