name: 'Bump version from tag'
description: 'Bumps a semver version from tag or fallback version'
inputs:
    token:
        description: 'Github token used by octokit (github API)'
        required: true
    build_number:
        description: 'Optional: used to generate the pre_release_version as {version}-alpha.{build_number}. (Default: 0)'
        required: false
    fallback_tag:
        description: 'Optional: used as fallback when no tag/release can be found on the repository.'
        required: false
    disable_inform:
        description: 'Disables the comment created by the script. (Default: false)'
        required: false
outputs:
    old_version:
        description: 'The latest tag found'
    new_version:
        description: 'The next calculated version'
    pre_release_version:
        description: 'Pre release version built from {new_version}-alpha.{build_number}'
runs:
    using: 'node16'
    main: 'dist/index.js'
